/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FwButton {
    }
    interface FwRating {
        "maxValue": number;
        "value": number;
    }
}
declare global {
    interface HTMLFwButtonElement extends Components.FwButton, HTMLStencilElement {
    }
    var HTMLFwButtonElement: {
        prototype: HTMLFwButtonElement;
        new (): HTMLFwButtonElement;
    };
    interface HTMLFwRatingElement extends Components.FwRating, HTMLStencilElement {
    }
    var HTMLFwRatingElement: {
        prototype: HTMLFwRatingElement;
        new (): HTMLFwRatingElement;
    };
    interface HTMLElementTagNameMap {
        "fw-button": HTMLFwButtonElement;
        "fw-rating": HTMLFwRatingElement;
    }
}
declare namespace LocalJSX {
    interface FwButton {
    }
    interface FwRating {
        "maxValue"?: number;
        "value"?: number;
    }
    interface IntrinsicElements {
        "fw-button": FwButton;
        "fw-rating": FwRating;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fw-button": LocalJSX.FwButton & JSXBase.HTMLAttributes<HTMLFwButtonElement>;
            "fw-rating": LocalJSX.FwRating & JSXBase.HTMLAttributes<HTMLFwRatingElement>;
        }
    }
}
